import app from "./lifecycle_full";
import { recentOrderActivity } from "./order_lifecycle";

const ADMIN="admin@wateroncall.ca";
function esc(v:any){return String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;")}
function cookie(req:Request,n:string){for(const p of (req.headers.get("Cookie")||"").split(";")){const [k,...v]=p.trim().split("=");if(k===n)return decodeURIComponent(v.join("="))}return null}
async function sha(v:string){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function user(req:Request,env:any){const t=cookie(req,"woc_session");if(!t)return null;return env.DB.prepare(`SELECT users.id,users.email,users.role FROM sessions JOIN users ON users.id=sessions.user_id WHERE sessions.token_hash=? AND datetime(sessions.expires_at)>datetime('now') LIMIT 1`).bind(await sha(t)).first<any>()}

async function orderInfo(env:any,id:string){return env.DB.prepare(`SELECT o.id,o.status,o.order_type,o.gallons,o.city,o.requested_date,o.created_at,u.full_name AS customer_name,u.email AS customer_email FROM orders o JOIN users u ON u.id=o.customer_id WHERE o.id=? LIMIT 1`).bind(id).first<any>()}
function page(order:any,rows:any[]){const events=rows.length?rows.map(r=>`<div class="event"><div class="dot"></div><div><strong>${esc(r.event_type).replaceAll('_',' ')}</strong><div>${r.from_status?`${esc(r.from_status)} → ${esc(r.to_status)}`:esc(r.to_status||'')}</div><div class="muted">${esc(r.created_at)} · ${esc(r.actor_role||'system')}${r.actor_user_id?` · ${esc(r.actor_user_id)}`:''}</div></div></div>`).join(''):`<div class="empty">No centralized activity has been recorded for this order yet. New lifecycle events will appear here.</div>`;return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Order Activity | Water OnCall</title><style>*{box-sizing:border-box}body{margin:0;background:#f5faff;color:#13283d;font-family:Inter,system-ui,sans-serif}.wrap{max-width:900px;margin:auto;padding:34px 20px}a{color:#0877f9;font-weight:800;text-decoration:none}.card{background:#fff;border:1px solid #dce8f3;border-radius:18px;padding:22px;margin-top:20px}.top{display:flex;justify-content:space-between;gap:20px;align-items:flex-start;flex-wrap:wrap}h1{color:#06325e;margin:8px 0}.badge{background:#eaf4ff;color:#0757a7;padding:7px 10px;border-radius:999px;font-weight:850}.summary{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.field{padding:12px;background:#f8fbfe;border-radius:11px}.field span,.muted{display:block;color:#6a7f92;font-size:12px}.event{display:grid;grid-template-columns:16px 1fr;gap:12px;padding:15px 0;border-bottom:1px solid #edf3f8}.dot{width:12px;height:12px;border-radius:50%;background:#0877f9;margin-top:4px}.empty{padding:30px;text-align:center;color:#6a7f92}@media(max-width:650px){.summary{grid-template-columns:1fr}}</style></head><body><div class="wrap"><a href="/admin">← Back to Admin</a><div class="card"><div class="top"><div><div class="muted">Order ${esc(order.id)}</div><h1>Order Activity</h1></div><span class="badge">${esc(order.status)}</span></div><div class="summary"><div class="field"><span>Customer</span><strong>${esc(order.customer_name||order.customer_email)}</strong></div><div class="field"><span>Delivery</span><strong>${Number(order.gallons||0).toLocaleString()} gal · ${esc(order.order_type)}</strong></div><div class="field"><span>Area</span><strong>${esc(order.city||'')}</strong></div></div></div><div class="card"><h2>Timeline</h2>${events}</div></div></body></html>`}

export default{async fetch(req:Request,env:any,ctx:ExecutionContext){const url=new URL(req.url);const m=url.pathname.match(/^\/admin\/orders\/([^/]+)\/activity$/);if(m&&req.method==="GET"){const u=await user(req,env);if(!u||u.email!==ADMIN)return Response.redirect(new URL('/login',req.url).toString(),302);const id=decodeURIComponent(m[1]);const order=await orderInfo(env,id);if(!order)return new Response('Order not found',{status:404});const rows=await recentOrderActivity(env,id,200);return new Response(page(order,rows),{headers:{"Content-Type":"text/html; charset=utf-8","Cache-Control":"no-store","X-Content-Type-Options":"nosniff","X-Frame-Options":"DENY"}})}return app.fetch(req,env,ctx)}};
