import app from "./launch_email";
import { recentNotifications } from "./notifications";

const ADMIN="admin@wateroncall.ca";
function esc(v:any){return String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;")}
function cookie(req:Request,n:string){for(const p of (req.headers.get("Cookie")||"").split(";")){const [k,...v]=p.trim().split("=");if(k===n)return decodeURIComponent(v.join("="))}return null}
async function sha(v:string){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function user(req:Request,env:any){const t=cookie(req,"woc_session");if(!t)return null;return env.DB.prepare(`SELECT users.id,users.email,users.role FROM sessions JOIN users ON users.id=sessions.user_id WHERE sessions.token_hash=? AND datetime(sessions.expires_at)>datetime('now') LIMIT 1`).bind(await sha(t)).first<any>()}

function page(rows:any[]){
 const counts={sent:0,failed:0,pending:0}; for(const r of rows){if(r.status in counts)(counts as any)[r.status]++}
 const body=rows.length?rows.map(r=>`<tr><td>${esc(r.created_at)}</td><td><strong>${esc(r.event_type)}</strong><div class="muted">${esc(r.subject||"")}</div></td><td>${esc(r.channel)}</td><td>${esc(r.recipient)}</td><td><span class="status ${esc(r.status)}">${esc(r.status)}</span>${r.error_message?`<div class="error">${esc(r.error_message)}</div>`:""}</td><td>${esc(r.provider||"")}${r.provider_message_id?`<div class="muted">${esc(r.provider_message_id)}</div>`:""}</td></tr>`).join(""):`<tr><td colspan="6" class="empty">No centralized notifications have been recorded yet. Existing notification paths will appear here as they are migrated.</td></tr>`;
 return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Notification History | Water OnCall</title><style>*{box-sizing:border-box}body{margin:0;background:#f5faff;color:#13283d;font-family:Inter,system-ui,sans-serif}.wrap{max-width:1250px;margin:auto;padding:34px 20px}.top{display:flex;justify-content:space-between;align-items:center;gap:20px;flex-wrap:wrap}h1{margin:0;color:#06325e}.back{color:#0877f9;text-decoration:none;font-weight:800}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin:24px 0}.card{background:#fff;border:1px solid #dce8f3;border-radius:16px;padding:18px}.n{font-size:30px;font-weight:900}.muted{color:#6a7f92;font-size:12px;margin-top:4px}.table{overflow:auto;background:#fff;border:1px solid #dce8f3;border-radius:16px}table{width:100%;border-collapse:collapse;min-width:950px}th,td{text-align:left;padding:13px;border-bottom:1px solid #edf3f8;vertical-align:top;font-size:13px}th{background:#f8fbfe;color:#50677d}.status{display:inline-block;padding:5px 8px;border-radius:999px;font-weight:850;text-transform:capitalize}.sent{background:#e4f8ef;color:#08764b}.failed{background:#fdeaea;color:#a32121}.pending{background:#fff3d8;color:#855d00}.error{color:#a32121;font-size:12px;margin-top:6px;max-width:360px}.empty{text-align:center;padding:45px;color:#6a7f92}@media(max-width:700px){.cards{grid-template-columns:1fr}}</style></head><body><div class="wrap"><div class="top"><div><h1>Notification History</h1><div class="muted">Email and SMS delivery audit trail</div></div><a class="back" href="/admin">← Back to Admin</a></div><div class="cards"><div class="card"><div class="n">${counts.sent}</div><strong>Sent</strong></div><div class="card"><div class="n">${counts.failed}</div><strong>Failed</strong></div><div class="card"><div class="n">${counts.pending}</div><strong>Pending</strong></div></div><div class="table"><table><thead><tr><th>Time</th><th>Event</th><th>Channel</th><th>Recipient</th><th>Status</th><th>Provider</th></tr></thead><tbody>${body}</tbody></table></div></div></body></html>`
}

export default{async fetch(req:Request,env:any,ctx:ExecutionContext){const url=new URL(req.url);if(req.method==="GET"&&url.pathname==="/admin/notifications"){const u=await user(req,env);if(!u||u.email!==ADMIN)return Response.redirect(new URL("/login",req.url).toString(),302);const rows=await recentNotifications(env,150);return new Response(page(rows),{headers:{"Content-Type":"text/html; charset=utf-8","Cache-Control":"no-store","X-Content-Type-Options":"nosniff","X-Frame-Options":"DENY"}})}return app.fetch(req,env,ctx)}};
