import app from './security_headers';
import { platformMode } from './pilot_rules';
const ADMIN='admin@wateroncall.ca';
function json(d:any,s=200,h:Record<string,string>={}){return new Response(JSON.stringify(d),{status:s,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',...h}})}
function cv(r:Request,n:string){for(const p of (r.headers.get('Cookie')||'').split(';')){const [k,...v]=p.trim().split('=');if(k===n)return decodeURIComponent(v.join('='))}return null}
async function sha(v:string){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function admin(r:Request,e:any){const t=cv(r,'woc_session');if(!t)return null;const u=await e.DB.prepare(`SELECT u.id,u.email FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND datetime(s.expires_at)>datetime('now') LIMIT 1`).bind(await sha(t)).first<any>();return u?.email===ADMIN?u:null}
async function ensure(env:any){await env.DB.prepare(`CREATE TABLE IF NOT EXISTS admin_test_context(admin_user_id TEXT PRIMARY KEY,view_role TEXT NOT NULL DEFAULT 'admin',updated_at TEXT NOT NULL DEFAULT(datetime('now')))`).run()}
async function api(req:Request,env:any){const a=await admin(req,env);if(!a)return json({error:'Administrator access required.'},403);const mode=await platformMode(env);if(mode?.mode!=='testing')return json({error:'Testing role switcher is only available in TESTING mode.'},403);await ensure(env);if(req.method==='GET'){const x=await env.DB.prepare(`SELECT view_role FROM admin_test_context WHERE admin_user_id=?`).bind(a.id).first<any>();return json({ok:true,view_role:x?.view_role||'admin',roles:['admin','customer','hauler','dispatcher','driver']})}let b:any={};try{b=await req.json()}catch{};const role=String(b.role||'admin');if(!['admin','customer','hauler','dispatcher','driver'].includes(role))return json({error:'Invalid test role.'},400);await env.DB.prepare(`INSERT INTO admin_test_context(admin_user_id,view_role) VALUES(?,?) ON CONFLICT(admin_user_id) DO UPDATE SET view_role=excluded.view_role,updated_at=datetime('now')`).bind(a.id,role).run();return json({ok:true,view_role:role,go:role==='admin'?'/admin':role==='customer'?'/account':role==='hauler'?'/hauler':role==='dispatcher'?'/dispatcher':'/driver'})}
function page(){return new Response(`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Testing Toolkit | Water OnCall</title><style>body{font-family:Inter,system-ui;background:#f5faff;color:#13283d;margin:0}main{max-width:700px;margin:auto;padding:40px 20px}.card{background:#fff;border:1px solid #dce8f3;border-radius:18px;padding:22px}h1{color:#06325e}button{width:100%;height:48px;margin:7px 0;border:1px solid #bdd0e1;border-radius:10px;background:#fff;color:#06325e;font-weight:850}button.active{background:#0877f9;color:#fff}.note{background:#fff3d8;border:1px solid #e9cc78;border-radius:10px;padding:13px;margin-bottom:16px}a{color:#0877f9;font-weight:800}</style></head><body><main><a href="/admin">← Admin</a><h1>Testing Toolkit</h1><div class="note">TESTING only. This lets the Admin review each portal without creating more email logins. It does not create real customers, charges or dispatches.</div><div class="card" id="roles"></div></main><script>async function load(){const r=await fetch('/api/admin/test-role'),d=await r.json();if(!r.ok){location='/login';return}document.getElementById('roles').innerHTML=d.roles.map(x=>'<button class="'+(x===d.view_role?'active':'')+'" onclick="setRole(\''+x+'\')">View as '+x[0].toUpperCase()+x.slice(1)+'</button>').join('')}async function setRole(role){const r=await fetch('/api/admin/test-role',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({role})}),d=await r.json();if(r.ok)location=d.go;else alert(d.error)}load()</script></body></html>`,{headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store','X-Frame-Options':'DENY'}})}
export default{async fetch(req:Request,env:any,ctx:ExecutionContext){const u=new URL(req.url);if(u.pathname==='/api/admin/test-role'&&(req.method==='GET'||req.method==='POST'))return api(req,env);if(u.pathname==='/admin/testing'&&req.method==='GET'){if(!(await admin(req,env)))return Response.redirect(new URL('/login',req.url).toString(),302);return page()}return app.fetch(req,env,ctx)}};
