import app from './admin_controls';
import { recordOrderActivity } from './order_lifecycle';
const ADMIN='admin@wateroncall.ca';
function json(d:any,s=200){return new Response(JSON.stringify(d),{status:s,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'}})}
function cv(req:Request,n:string){for(const p of (req.headers.get('Cookie')||'').split(';')){const [k,...v]=p.trim().split('=');if(k===n)return decodeURIComponent(v.join('='))}return null}
async function sha(v:string){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function admin(req:Request,env:any){const t=cv(req,'woc_session');if(!t)return null;const u=await env.DB.prepare(`SELECT users.id,users.email FROM sessions JOIN users ON users.id=sessions.user_id WHERE sessions.token_hash=? AND datetime(sessions.expires_at)>datetime('now') LIMIT 1`).bind(await sha(t)).first<any>();return u?.email===ADMIN?u:null}
async function override(req:Request,env:any,id:string){const u=await admin(req,env);if(!u)return json({error:'Administrator access required.'},403);let b:any={};try{b=await req.json()}catch{};const reason=String(b.reason||'').trim();if(reason.length<5)return json({error:'Enter a reason for the override.'},400);const order=await env.DB.prepare(`SELECT id,status FROM orders WHERE id=?`).bind(id).first<any>();if(!order)return json({error:'Order not found.'},404);const action=String(b.action||'');let before:any={status:order.status},after:any={};if(action==='status'){const status=String(b.status||'');if(!['requested','offered','accepted','assigned','en_route','delivered','completed','cancelled'].includes(status))return json({error:'Invalid status.'},400);await env.DB.prepare(`UPDATE orders SET status=?,updated_at=datetime('now') WHERE id=?`).bind(status,id).run();after={status};await recordOrderActivity(env,{orderId:id,eventType:'admin_status_override',fromStatus:order.status,toStatus:status,actorUserId:u.id,actorRole:'admin',details:{reason}})}else if(action==='hold_payout'){await env.DB.prepare(`UPDATE hauler_payout_ledger SET status='held',hold_reason=?,updated_at=datetime('now') WHERE order_id=?`).bind(reason,id).run();after={payout_status:'held'}}else if(action==='release_payout'){await env.DB.prepare(`UPDATE hauler_payout_ledger SET status='eligible',hold_reason=NULL,updated_at=datetime('now') WHERE order_id=? AND status='held'`).bind(id).run();after={payout_status:'eligible'}}else{return json({error:'Unsupported override action.'},400)}await env.DB.prepare(`INSERT INTO admin_overrides(id,admin_user_id,order_id,action,reason,before_json,after_json) VALUES(?,?,?,?,?,?,?)`).bind(crypto.randomUUID(),u.id,id,action,reason,JSON.stringify(before),JSON.stringify(after)).run();return json({ok:true,action,...after})}
export default{async fetch(req:Request,env:any,ctx:ExecutionContext){const u=new URL(req.url),m=u.pathname.match(/^\/api\/admin\/orders\/([^/]+)\/override$/);if(m&&req.method==='POST')return override(req,env,decodeURIComponent(m[1]));return app.fetch(req,env,ctx)}};
