import app from './marketplace_guard';
import { cancellationDecision } from './cancellation_policy';
import { recordOrderActivity } from './order_lifecycle';
function json(d:any,s=200){return new Response(JSON.stringify(d),{status:s,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'}})}
function cv(r:Request,n:string){for(const p of (r.headers.get('Cookie')||'').split(';')){const [k,...v]=p.trim().split('=');if(k===n)return decodeURIComponent(v.join('='))}return null}
async function sha(v:string){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function user(r:Request,e:any){const t=cv(r,'woc_session');if(!t)return null;return e.DB.prepare(`SELECT u.id,u.email FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND datetime(s.expires_at)>datetime('now') LIMIT 1`).bind(await sha(t)).first<any>()}
async function fee(env:any){await env.DB.prepare(`CREATE TABLE IF NOT EXISTS platform_settings(key TEXT PRIMARY KEY,value TEXT NOT NULL,updated_at TEXT NOT NULL DEFAULT(datetime('now')),updated_by TEXT)`).run();const x=await env.DB.prepare(`SELECT value FROM platform_settings WHERE key='service_fee_cents'`).first<any>();return Math.max(0,Number(x?.value||599))}
async function cancel(req:Request,env:any,id:string){const u=await user(req,env);if(!u)return json({error:'Please sign in again.'},401);const o=await env.DB.prepare(`SELECT id,status,requested_date FROM orders WHERE id=? AND customer_id=? LIMIT 1`).bind(id,u.id).first<any>();if(!o)return json({error:'Order not found.'},404);const d=cancellationDecision(String(o.status),o.requested_date, new Date(),await fee(env));if(!d.allowed)return json({error:d.reason,requires_admin:d.requires_admin},409);await env.DB.prepare(`UPDATE orders SET status='cancelled',updated_at=datetime('now') WHERE id=? AND customer_id=? AND status=?`).bind(id,u.id,o.status).run();await env.DB.prepare(`UPDATE marketplace_offers SET status='cancelled',responded_at=datetime('now') WHERE order_id=? AND status='pending'`).bind(id).run();await recordOrderActivity(env,{orderId:id,eventType:'customer_cancelled',fromStatus:o.status,toStatus:'cancelled',actorUserId:u.id,actorRole:'customer',details:{cancellation_charge_cents:d.charge_cents,policy_reason:d.reason}});return json({ok:true,status:'cancelled',cancellation_charge_cents:d.charge_cents,payment_action:d.charge_cents>0?'charge_when_stripe_connected':'none'})}
export default{async fetch(req:Request,env:any,ctx:ExecutionContext){const u=new URL(req.url),m=u.pathname.match(/^\/api\/customer\/orders\/([^/]+)\/cancel$/);if(m&&req.method==='POST')return cancel(req,env,decodeURIComponent(m[1]));return app.fetch(req,env,ctx)}};
