import app from './testing_gate';
import { ensurePilotSchema } from './pilot_foundation';
function json(d:any,s=200){return new Response(JSON.stringify(d),{status:s,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'}})}
function cv(r:Request,n:string){for(const p of (r.headers.get('Cookie')||'').split(';')){const [k,...v]=p.trim().split('=');if(k===n)return decodeURIComponent(v.join('='))}return null}
async function sha(v:string){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function hauler(r:Request,e:any){const t=cv(r,'woc_session');if(!t)return null;return e.DB.prepare(`SELECT u.id,u.email,h.business_name,h.status FROM sessions s JOIN users u ON u.id=s.user_id JOIN hauler_profiles h ON h.user_id=u.id WHERE s.token_hash=? AND datetime(s.expires_at)>datetime('now') AND h.status='approved' LIMIT 1`).bind(await sha(t)).first<any>()}
async function pricing(req:Request,env:any){const h=await hauler(req,env);if(!h)return json({error:'Approved hauler access required.'},403);await ensurePilotSchema(env);if(req.method==='GET'){const rows=await env.DB.prepare(`SELECT * FROM hauler_truck_pricing WHERE hauler_id=? ORDER BY capacity_gallons`).bind(h.id).all();return json({ok:true,pricing:rows.results||[]})}let b:any={};try{b=await req.json()}catch{};const cap=Math.round(Number(b.capacity_gallons)),base=Math.round(Number(b.base_price_cents)),fuel=Math.max(0,Math.round(Number(b.fuel_surcharge_cents||0))),includedKm=Math.max(0,Number(b.included_km??10)),blockKm=Math.max(.1,Number(b.extra_distance_block_km??5)),extraKm=Math.max(0,Math.round(Number(b.extra_distance_block_cents??500))),includedHose=Math.max(0,Number(b.included_hose_ft??25)),hoseBlock=Math.max(1,Number(b.extra_hose_block_ft??25)),extraHose=Math.max(0,Math.round(Number(b.extra_hose_block_cents??500)));if(!Number.isFinite(cap)||cap<500||cap>10000||!Number.isFinite(base)||base<0)return json({error:'Enter a valid truck capacity and base delivery price.'},400);await env.DB.prepare(`INSERT INTO hauler_truck_pricing(id,hauler_id,capacity_gallons,base_price_cents,fuel_surcharge_cents,included_km,extra_distance_block_km,extra_distance_block_cents,included_hose_ft,extra_hose_block_ft,extra_hose_block_cents,active) VALUES(?,?,?,?,?,?,?,?,?,?,?,1) ON CONFLICT(hauler_id,capacity_gallons) DO UPDATE SET base_price_cents=excluded.base_price_cents,fuel_surcharge_cents=excluded.fuel_surcharge_cents,included_km=excluded.included_km,extra_distance_block_km=excluded.extra_distance_block_km,extra_distance_block_cents=excluded.extra_distance_block_cents,included_hose_ft=excluded.included_hose_ft,extra_hose_block_ft=excluded.extra_hose_block_ft,extra_hose_block_cents=excluded.extra_hose_block_cents,active=1,updated_at=datetime('now')`).bind(crypto.randomUUID(),h.id,cap,base,fuel,includedKm,blockKm,extraKm,includedHose,hoseBlock,extraHose).run();return json({ok:true})}
async function stations(req:Request,env:any){const h=await hauler(req,env);if(!h)return json({error:'Approved hauler access required.'},403);await ensurePilotSchema(env);if(req.method==='GET'){const rows=await env.DB.prepare(`SELECT ws.*,COALESCE(hws.active,0) AS selected,COALESCE(hws.is_preferred,0) AS preferred FROM water_stations ws LEFT JOIN hauler_water_stations hws ON hws.station_id=ws.id AND hws.hauler_id=? WHERE ws.status='active' ORDER BY ws.city,ws.name`).bind(h.id).all();return json({ok:true,stations:rows.results||[]})}let b:any={};try{b=await req.json()}catch{};const name=String(b.name||'').trim(),address=String(b.address||'').trim();if(name&&address){const id=crypto.randomUUID();await env.DB.prepare(`INSERT INTO water_stations(id,name,address,city,province,postal_code,google_place_id,lat,lng,created_by) VALUES(?,?,?,?,?,?,?,?,?,?)`).bind(id,name,address,String(b.city||''),String(b.province||'ON'),String(b.postal_code||''),String(b.google_place_id||'')||null,Number(b.lat)||null,Number(b.lng)||null,h.id).run();await env.DB.prepare(`INSERT INTO hauler_water_stations(hauler_id,station_id,active,is_preferred) VALUES(?,?,1,?)`).bind(h.id,id,b.preferred?1:0).run();return json({ok:true,station_id:id})}const stationId=String(b.station_id||'');if(!stationId)return json({error:'Choose or add a water station.'},400);await env.DB.prepare(`INSERT INTO hauler_water_stations(hauler_id,station_id,active,is_preferred) VALUES(?,?,?,?) ON CONFLICT(hauler_id,station_id) DO UPDATE SET active=excluded.active,is_preferred=excluded.is_preferred`).bind(h.id,stationId,b.active===false?0:1,b.preferred?1:0).run();return json({ok:true})}
export default{async fetch(req:Request,env:any,ctx:ExecutionContext){const u=new URL(req.url);if(u.pathname==='/api/hauler/pricing-v2'&&(req.method==='GET'||req.method==='POST'))return pricing(req,env);if(u.pathname==='/api/hauler/water-stations'&&(req.method==='GET'||req.method==='POST'))return stations(req,env);return app.fetch(req,env,ctx)}};
