import app from './integration_nav';
import { platformMode } from './pilot_rules';
function json(d:any,s=200){return new Response(JSON.stringify(d),{status:s,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'}})}
function cv(r:Request,n:string){for(const p of (r.headers.get('Cookie')||'').split(';')){const [k,...v]=p.trim().split('=');if(k===n)return decodeURIComponent(v.join('='))}return null}
async function sha(v:string){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function hauler(r:Request,e:any){const t=cv(r,'woc_session');if(!t)return null;return e.DB.prepare(`SELECT u.id FROM sessions s JOIN users u ON u.id=s.user_id JOIN hauler_profiles hp ON hp.user_id=u.id WHERE s.token_hash=? AND datetime(s.expires_at)>datetime('now') AND hp.status='approved' LIMIT 1`).bind(await sha(t)).first<any>()}
async function customerId(env:any,orderId:string){return env.DB.prepare(`SELECT customer_id FROM orders WHERE id=? LIMIT 1`).bind(orderId).first<any>()}
async function excluded(env:any,cid:string,hid:string){const x=await env.DB.prepare(`SELECT preference FROM customer_hauler_preferences WHERE customer_id=? AND hauler_id=? AND preference='excluded' LIMIT 1`).bind(cid,hid).first();return !!x}
export default{async fetch(req:Request,env:any,ctx:ExecutionContext){const u=new URL(req.url),mode=await platformMode(env);const decision=u.pathname.match(/^\/api\/hauler\/offers\/([^/]+)\/(accept|decline)$/);if(decision&&req.method==='POST'){if(mode?.mode!=='live'||!mode?.dispatch_enabled)return json({error:'Water OnCall is in testing mode. Real delivery acceptance is disabled.'},503);const h=await hauler(req,env);if(!h)return json({error:'Approved hauler access required.'},403);const o=await customerId(env,decodeURIComponent(decision[1]));if(!o)return json({error:'Order not found.'},404);if(await excluded(env,o.customer_id,h.id))return json({error:'This customer has excluded your company from this request.'},403)}return app.fetch(req,env,ctx)}};
