import app from "./admin_order_activity";

export async function ensurePilotSchema(env:any):Promise<void>{
 await env.DB.prepare(`CREATE TABLE IF NOT EXISTS water_stations(id TEXT PRIMARY KEY,name TEXT NOT NULL,address TEXT NOT NULL,city TEXT,province TEXT NOT NULL DEFAULT 'ON',postal_code TEXT,google_place_id TEXT,lat REAL,lng REAL,status TEXT NOT NULL DEFAULT 'active',created_by TEXT,created_at TEXT NOT NULL DEFAULT(datetime('now')),updated_at TEXT NOT NULL DEFAULT(datetime('now')))`).run();
 await env.DB.prepare(`CREATE TABLE IF NOT EXISTS hauler_water_stations(hauler_id TEXT NOT NULL,station_id TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 1,is_preferred INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL DEFAULT(datetime('now')),PRIMARY KEY(hauler_id,station_id),FOREIGN KEY(hauler_id) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(station_id) REFERENCES water_stations(id) ON DELETE CASCADE)`).run();
 await env.DB.prepare(`CREATE TABLE IF NOT EXISTS hauler_truck_pricing(id TEXT PRIMARY KEY,hauler_id TEXT NOT NULL,capacity_gallons INTEGER NOT NULL,base_price_cents INTEGER NOT NULL,fuel_surcharge_cents INTEGER NOT NULL DEFAULT 0,included_km REAL NOT NULL DEFAULT 10,extra_distance_block_km REAL NOT NULL DEFAULT 5,extra_distance_block_cents INTEGER NOT NULL DEFAULT 500,included_hose_ft REAL NOT NULL DEFAULT 25,extra_hose_block_ft REAL NOT NULL DEFAULT 25,extra_hose_block_cents INTEGER NOT NULL DEFAULT 500,active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL DEFAULT(datetime('now')),updated_at TEXT NOT NULL DEFAULT(datetime('now')),UNIQUE(hauler_id,capacity_gallons),FOREIGN KEY(hauler_id) REFERENCES users(id) ON DELETE CASCADE)`).run();
 await env.DB.prepare(`CREATE TABLE IF NOT EXISTS customer_payment_readiness(user_id TEXT PRIMARY KEY,stripe_customer_id TEXT,stripe_payment_method_id TEXT,payment_method_ready INTEGER NOT NULL DEFAULT 0,updated_at TEXT NOT NULL DEFAULT(datetime('now')),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE)`).run();
 await env.DB.prepare(`CREATE TABLE IF NOT EXISTS payout_settings(id INTEGER PRIMARY KEY CHECK(id=1),hold_days INTEGER NOT NULL DEFAULT 3,automatic_payouts INTEGER NOT NULL DEFAULT 0,updated_at TEXT NOT NULL DEFAULT(datetime('now')))`).run();
 await env.DB.prepare(`INSERT OR IGNORE INTO payout_settings(id,hold_days,automatic_payouts) VALUES(1,3,0)`).run();
 await env.DB.prepare(`CREATE TABLE IF NOT EXISTS hauler_payout_ledger(id TEXT PRIMARY KEY,hauler_id TEXT NOT NULL,order_id TEXT NOT NULL UNIQUE,amount_cents INTEGER NOT NULL,eligible_at TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','held','eligible','paid','reversed')),hold_reason TEXT,payout_batch_id TEXT,created_at TEXT NOT NULL DEFAULT(datetime('now')),updated_at TEXT NOT NULL DEFAULT(datetime('now')),FOREIGN KEY(hauler_id) REFERENCES users(id),FOREIGN KEY(order_id) REFERENCES orders(id))`).run();
 await env.DB.prepare(`CREATE TABLE IF NOT EXISTS customer_hauler_preferences(customer_id TEXT NOT NULL,hauler_id TEXT NOT NULL,preference TEXT NOT NULL CHECK(preference IN ('preferred','allowed','excluded')),created_at TEXT NOT NULL DEFAULT(datetime('now')),updated_at TEXT NOT NULL DEFAULT(datetime('now')),PRIMARY KEY(customer_id,hauler_id),FOREIGN KEY(customer_id) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(hauler_id) REFERENCES users(id) ON DELETE CASCADE)`).run();
 await env.DB.prepare(`CREATE TABLE IF NOT EXISTS admin_overrides(id TEXT PRIMARY KEY,admin_user_id TEXT NOT NULL,order_id TEXT,action TEXT NOT NULL,reason TEXT NOT NULL,before_json TEXT,after_json TEXT,created_at TEXT NOT NULL DEFAULT(datetime('now')))`).run();
}

async function readiness(req:Request,env:any){
 await ensurePilotSchema(env);
 const cookie=(req.headers.get('Cookie')||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('woc_session='));if(!cookie)return new Response(JSON.stringify({ready:false,email_verified:false,mobile_verified:false,payment_method:false}),{status:401,headers:{'Content-Type':'application/json'}});
 const token=decodeURIComponent(cookie.slice('woc_session='.length));const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(token));const hash=[...new Uint8Array(digest)].map(x=>x.toString(16).padStart(2,'0')).join('');
 const u=await env.DB.prepare(`SELECT users.id,users.email_verified_at FROM sessions JOIN users ON users.id=sessions.user_id WHERE sessions.token_hash=? AND datetime(sessions.expires_at)>datetime('now') LIMIT 1`).bind(hash).first<any>();if(!u)return new Response(JSON.stringify({ready:false}),{status:401,headers:{'Content-Type':'application/json'}});
 const phone=await env.DB.prepare(`SELECT user_id FROM verified_phones WHERE user_id=? LIMIT 1`).bind(u.id).first();const pay=await env.DB.prepare(`SELECT payment_method_ready FROM customer_payment_readiness WHERE user_id=? LIMIT 1`).bind(u.id).first<any>();
 const data={ready:!!u.email_verified_at&&!!phone&&!!pay?.payment_method_ready,email_verified:!!u.email_verified_at,mobile_verified:!!phone,payment_method:!!pay?.payment_method_ready};return new Response(JSON.stringify(data),{headers:{'Content-Type':'application/json','Cache-Control':'no-store'}});
}

export default{async fetch(req:Request,env:any,ctx:ExecutionContext){const url=new URL(req.url);if(url.pathname==='/api/customer/order-readiness'&&req.method==='GET')return readiness(req,env);return app.fetch(req,env,ctx)}};
