import app from './test_context_router';
import { platformMode } from './pilot_rules';
const ADMIN='admin@wateroncall.ca';
function cv(r:Request,n:string){for(const p of (r.headers.get('Cookie')||'').split(';')){const [k,...v]=p.trim().split('=');if(k===n)return decodeURIComponent(v.join('='))}return null}
async function sha(v:string){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function isAdmin(r:Request,e:any){const t=cv(r,'woc_session');if(!t)return false;const u=await e.DB.prepare(`SELECT users.email FROM sessions JOIN users ON users.id=sessions.user_id WHERE sessions.token_hash=? AND datetime(sessions.expires_at)>datetime('now') LIMIT 1`).bind(await sha(t)).first<any>();return u?.email===ADMIN}
const JS=`document.addEventListener('DOMContentLoaded',()=>{const s=document.getElementById('woc-test-role');if(!s)return;s.addEventListener('change',async()=>{const r=await fetch('/api/admin/test-role',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({role:s.value})});const d=await r.json();if(r.ok)location=d.go;else alert(d.error||'Unable to change test view.')})});`;
async function enhance(r:Response,env:any){if(!r.headers.get('Content-Type')?.includes('text/html'))return r;let html=await r.text();let role='admin';try{const rows=await env.DB.prepare(`SELECT view_role FROM admin_test_context a JOIN users u ON u.id=a.admin_user_id WHERE u.email=? LIMIT 1`).bind(ADMIN).first<any>();role=rows?.view_role||'admin'}catch{}const options=[['customer','Customer'],['hauler','Water Hauler'],['dispatcher','Dispatcher'],['driver','Driver'],['admin','Admin']].map(([v,l])=>`<option value="${v}"${role===v?' selected':''}>${l}</option>`).join('');const bar=`<div id="woc-role-bar" style="position:relative;z-index:100000;background:#06325e;color:white;padding:9px 14px;display:flex;justify-content:center;align-items:center;gap:10px;font-family:Inter,system-ui,sans-serif;font-size:13px;font-weight:800"><span>TESTING — Viewing as:</span><select id="woc-test-role" style="height:34px;border:0;border-radius:7px;padding:0 30px 0 10px;font:inherit;color:#13283d;background:white">${options}</select></div>`;html=html.replace(/<body([^>]*)>/i,`<body$1>${bar}`).replace('</body>','<script src="/test-role-bar.js" defer></script></body>');const h=new Headers(r.headers);h.delete('Content-Length');h.set('Cache-Control','no-store');return new Response(html,{status:r.status,statusText:r.statusText,headers:h})}
export default{async fetch(req:Request,env:any,ctx:ExecutionContext){const u=new URL(req.url);if(u.pathname==='/test-role-bar.js'&&req.method==='GET')return new Response(JS,{headers:{'Content-Type':'text/javascript; charset=utf-8','Cache-Control':'no-store'}});const r=await app.fetch(req,env,ctx);if(req.method==='GET'&&await isAdmin(req,env)&&(await platformMode(env))?.mode==='testing'&&r.headers.get('Content-Type')?.includes('text/html'))return enhance(r,env);return r}};
